version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tss
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres
  redis:
    image: redis:alpine
  celery:
    restart: always
    build: .
    # command: celery -A backend worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - django
  celery-beat:
    restart: always
    build: .
    # command: celery -A backend beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - django
volumes:
  db-data:
